name: Spell Check and Deploy

on:
  push:
    branches:
      - main

jobs:
  spell-check:
    name: Spell Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run spell check
        uses: rojopolis/spellcheck-github-actions@0.20.0
        with:
          config: .spellcheck.yml

  deploy:
    name: Deploy to Hosting Branch
    runs-on: ubuntu-latest
    needs: spell-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy static assets
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git switch --orphan gh-pages
          git rm -rf .
          cp -r assets/* .
          git add .
          git commit -m "Deploy static assets"
          git push --force origin gh-pages